version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime
      - IMAGE_TAG=$(date +%Y-%d-%m.%H.%M.%S)
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 082334196434.dkr.ecr.ap-northeast-2.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t skills-product-ecr .
      - docker tag skills-product-ecr:latest 082334196434.dkr.ecr.ap-northeast-2.amazonaws.com/skills-product-ecr:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 082334196434.dkr.ecr.ap-northeast-2.amazonaws.com/skills-product-ecr:$IMAGE_TAG
      - sed "s|<IMAGE_TAG>|$IMAGE_TAG|" -i taskdef.json
      - cat taskdef.json
artifacts:
  files: 
    - taskdef.json
    - appspec.yml
